### ISSUE TITLE
Display does not refresh on my Prestigio PER5664BC

### ISSUE THREAD

**Issue by asiekierka** [S-trace/eView#1]
Hello,

eView seems to work perfectly on my Prestigio PER5664BC (seems to be similar to the Digma R60G) after a manual GTK_parts/eView installation, but the screen does not refresh - using /usr/bin/refresh_display works, though. Any ideas on what could be the reason?

**Comment by asiekierka** [comment]
After further debugging, I found that this issue was introduced in eView 063. eView 062 works fine - 063 does not.

**Comment by S-trace** [comment]
This bug seems to be caused by display refresh IOCTL autodetection, which was introduced in https://github.com/S-trace/eView/commit/a61196bfefeef48a3edd74c9fe2a9ce70149f9af commit. 
Can You show me eView debug log?

**Comment by asiekierka** [comment]
For 062 or 063?

**Comment by S-trace** [comment]
For 063. You can also play with refresh_type file in eView configuration directory (write 1 or 2 into it and see, what will change).
Looks like 2 should enable display refresh in 063 at Your device.

**Comment by S-trace** [comment]
Hello.
Please test this build: https://www.dropbox.com/s/jhxduhmf1jyfygs/eView064t3.zip?dl=1

**Comment by S-trace** [comment]
Please run eView_remover to purge old configuration filesbefore testing it.

**Comment by asiekierka** [comment]
It works now, thank you very much.
