### ISSUE TITLE
Черный экран при запуске.

### ISSUE THREAD

**Issue by viteo** [S-trace/eView#2]
Digma e605. Старые версии на старых прошивках запускались в 2013, сейчас обновил прошивку читалки (e625_20140304_rev1) и eView перестал работать: использую последнюю доступную версию 064t2 . Запускаю, экран окрашивается в черный. Сразу думал, что просто зависла читалка, но методом тыка (воткнул usb), экран обновился и я оказался в корне файловой системы. Вслепую и перетыкивая кабель для обновления экрана, можно зайти в папки и даже запустить просмотр комиксов, но обновление экрана происходит только через передергивание. 

GTK_parts 4, похоже, не устанавливается, т.к. экран так же гаснет. передергивание шнура не помогает. Ставил другую версию, GTK_parts 3 (в сообщениях форума нашел), она установилась.

Версия eView 063 с такой же проблемой. 062 запустилась, вроде бы, без проблем.

лог 064t2:
Detecting hardware
Found LED control at file /sys/class/leds/charger-led/brightness
Found APM power control via libapm
Found sysfs sleep trigger at file /sys/power/state
Backlight control not found
Hardware detect finished
writing 2 to /sys/class/leds/charger-led/brightness
Executing 'uname -a'
Linux boeye 2.6.25-dirty #758 Tue Feb 18 15:52:31 CST 2014 armv5tejl GNU/Linux
X is down! Assuming QT
trim_line called for line '4
'
Read '4' from /home/root/.GTK_parts.version
Trying to start Xfbdev
Executing 'Xfbdev :0 -br -pn -hide-cursor -dpi 150 -rgba vrgb & '
_XSERVTransSocketOpenCOTSServer: Unable to open socket for inet6
_XSERVTransOpen: transport open failed for inet6/boeye:0
_XSERVTransMakeAllCOTSServerListeners: failed to open listener for inet6
error opening security policy file /usr/lib/xserver/SecurityPolicy
Extended Input Devices not yet supported. Impelement it at line 637 in kinput.c
Failed to open TSLib device, tried /dev/ts /dev/touchscreen/0 .
Try setting TSLIB_TSDEVICE to valid /dev entry?
Xfbdev started after 0,6 seconds
trim_line called for line '86400
'
Sleep timeout is 86400
Executing 'dbus-send --print-reply --type=method_call --dest=com.sibrary.BoeyeServer /PowerManager com.sibrary.Service.PowerManager.setSuspendTime int32:86400'
method return sender=:1.1 -> dest=:1.16 reply_serial=2
trim_line called for line '/usr/share/ScreenSaver/screensaver.png
'
read /usr/share/ScreenSaver/screensaver.png
Reading next screensaver filename failed
Process closed
GET_CWD=/
Starting eView in directory '/'
GET_CWD=/
Reading crop from /.eView/crop (1)
UNABLE TO OPEN /.eView/split_spreads SETTING FILE FOR READ! IT'S BAD!
writing 0 to /.eView/split_spreads
Reading rotate from /.eView/rotate (0)
Reading frame from /.eView/frame (0)
Reading keepaspect from /.eView/keepaspect (1)
Reading manga from /.eView/manga (0)
UNABLE TO OPEN /.eView/web_manga_mode SETTING FILE FOR READ! IT'S BAD!
writing 0 to /.eView/web_manga_mode
UNABLE TO OPEN /.eView/overlap SETTING FILE FOR READ! IT'S BAD!
writing 0 to /.eView/overlap
Reading fm_toggle from /.eView/fm_toggle (0)
Reading move_toggle from /.eView/move_toggle (1)
Reading speed_toggle from /.eView/speed_toggle (0)
Reading show_clock from /.eView/show_clock (1)
Reading top_panel_active from /.eView/top_panel_active (1)
Reading loop_dir from /.eView/loop_dir (0)
Reading double_refresh from /.eView/double_refresh (0)
Reading viewed_pages from /.eView/viewed_pages (0)
Reading preload_enable from /.eView/preload_enable (1)
Reading caching_enable from /.eView/caching_enable (1)
Reading suppress_panel from /.eView/suppress_panel (0)
Reading show_hidden_files from /.eView/show_hidden_files (0)
Reading LED_notify from /.eView/LED_notify (1)
Reading backlight from /.eView/backlight (0)
Reading sleep_timeout from /.eView/sleep_timeout (60)
Reading HD_scaling from /.eView/HD_scaling (0)
Reading boost_contrast from /.eView/boost_contrast (0)
Reading refresh_type from /.eView/refresh_type (1)
Reading top panel configuration
Reading top_panel.path from /.eView/top_panel.path ((null)) successed
Reading top_panel.selected_name from /.eView/top_panel.selected_name ((null)) successed
Reading top_panel.archive_cwd from /.eView/top_panel.archive_cwd failed
Reading top_panel.archive_list from /.eView/top_panel.archive_list ((null)) successed
Reading top_panel.last_name from /.eView/top_panel.last_name failed
Reading top_panel.archive_stack from '/.eView/top_panel.archive_stack' (archive stack)
Reading 0 element from '/.eView/top_panel.archive_stack' (archive stack)
trim_line called for line 'filesystem
'
Reading 1 element from '/.eView/top_panel.archive_stack' (archive stack)
Readed empty line, break
Readed 1 elements from '/.eView/top_panel.archive_stack' (archive stack)
Reading bottom panel configuration
Reading bottom_panel.path from /.eView/bottom_panel.path ((null)) successed
Reading bottom_panel.selected_name from /.eView/bottom_panel.selected_name ((null)) successed
Reading bottom_panel.archive_cwd from /.eView/bottom_panel.archive_cwd failed
Reading bottom_panel.archive_list from /.eView/bottom_panel.archive_list ((null)) successed
Reading bottom_panel.last_name from /.eView/bottom_panel.last_name failed
Reading bottom_panel.archive_stack from '/.eView/bottom_panel.archive_stack' (archive stack)
Reading 0 element from '/.eView/bottom_panel.archive_stack' (archive stack)
trim_line called for line 'filesystem
'
Reading 1 element from '/.eView/bottom_panel.archive_stack' (archive stack)
Readed empty line, break
Readed 1 elements from '/.eView/bottom_panel.archive_stack' (archive stack)
Show message 'eView запускается', data: ' Пожалуйста, подождите! '

(eView064t2_russian-debug.app:804): Gtk-WARNING **: Unable to locate theme engine in module_path: "hcengine",

(eView064t2_russian-debug.app:804): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(eView064t2_russian-debug.app:804): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(eView064t2_russian-debug.app:804): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(eView064t2_russian-debug.app:804): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(eView064t2_russian-debug.app:804): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(eView064t2_russian-debug.app:804): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(eView064t2_russian-debug.app:804): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
constructing window 594x794
writing 4 to /sys/class/leds/charger-led/brightness
GET_CWD=/media/mmcblk0p1
Adding 1 dir '../'
Adding 3 dir 'Dict/'
Adding 4 dir 'Digital Editions/'
Adding 5 dir 'Documents/'
Adding 6 dir 'Memo/'
Adding 7 dir 'Music/'
Adding 8 dir 'Pictures/'
Adding 9 file 'eView_debug_log.txt', size 5,70 K 
Selecting file 'Pictures/'
Trying to find iter for name 'Pictures/'
Interface was locked, panel focus change signal ignored!
Trying to find iter for name 'Pictures/'
writing 0 to /sys/class/leds/charger-led/brightness
Selecting file 'Pictures/'
Trying to find iter for name 'Pictures/'
Preloading screensaver /usr/share/ScreenSaver/screensaver.png
Going to load '/usr/share/ScreenSaver/screensaver.png' (enable_actions=0)
CACHED IMAGE IS WRONG!!! have '', want '/usr/share/ScreenSaver/screensaver.png'
PRELOADED IMAGE IS WRONG!!! have '', want '/usr/share/ScreenSaver/screensaver.png'
Loading /usr/share/ScreenSaver/screensaver.png from file!
Resetting image 0x38fb8
pixbuf (nil) unreferenced
pixbuf 0xfa800 loaded from file
image_resize called
calculate_scaling_dimensions called (image 800x600, display 794x594)
scale_width=0,990000, scale_height=0,992500, scale=0,990000
new_width=594, new_height=792
scaling pic from 600x800 to 594x792
pixbuf 0xfa800 unreferenced
Sleep timeout thread started (timer=60)
writing 0 to /sys/class/leds/charger-led/brightness
Trying to find iter for name 'eView_debug_log.txt'
Trying to find iter for name '../'
Trying to find iter for name 'eView_debug_log.txt'
CWD=/media/mmcblk0p1
Trying to find iter for name 'Pictures/'
CWD=/media/mmcblk0p1
writing  to /.eView/top_panel.last_name
'Pictures/' clicked
writing 4 to /sys/class/leds/charger-led/brightness
GET_CWD=/media/mmcblk0p1/Pictures
Adding 1 dir '../'
Adding 4 dir 'e-ink/'
Adding 13 dir 'kindle/'
Adding 2 file 'GTK_parts.sh', size 4,83 M 
Adding 3 file 'GTK_parts1.sh', size 4,82 M 
Adding 5 file 'eView062_russian.app', size 78,77 K 
Adding 6 file 'eView063_russian-debug.app', size 131,00 K 
Adding 7 file 'eView063_russian.app', size 90,96 K 
Adding 8 file 'eView064t2_russian-debug.app', size 143,00 K 
Adding 9 file 'eView064t2_russian-installer.sh', size 58,14 K 
Adding 10 file 'eView064t2_russian.app', size 94,97 K 
Adding 11 file 'eView_remover.sh', size 443 B 
Adding 12 file 'eView_reset_configuration.sh', size 25 B 
Selecting file 'Pictures/'
Trying to find iter for name 'Pictures/'
Iter not found!
writing 0 to /sys/class/leds/charger-led/brightness
Trying to find iter for name '../'
writing  to /.eView/top_panel.last_name
writing /media/mmcblk0p1/Pictures/ to /.eView/top_panel.path
Shutting down eView
writing ../ to /.eView/top_panel.selected_name
writing ../ to /.eView/bottom_panel.selected_name
Shutting down Xfbdev
Executing 'killall Xfbdev'
Executing 'dbus-send --print-reply --type=method_call --dest=com.sibrary.BoeyeServer /PowerManager com.sibrary.Service.PowerManager.setSuspendTime int32:86400'
FreeFontPath: FPE "built-ins" refcount is 2, should be 1; fixing.
method return sender=:1.1 -> dest=:1.17 reply_serial=2

eView shutudown done. Bye! =^_^=/~

**Comment by S-trace** [comment]
Приветствую. 
Судя по логу, установлена четвёртая версия GTK_parts (Read '4' from /home/root/.GTK_parts.version) - без них бы eView попросту не запустился бы. 

Видимо, проблема кроется в том, что (как и в Issue 1) механизм обновления дисплея по какой-то причине автоопределяется неправильно (как для прошивок на базе GTK: Reading refresh_type from /.eView/refresh_type (1)), либо вообще неизвестен на данный момент. 
Функционал автоопределения механизма обновления был добавлен в коммите https://github.com/S-trace/eView/commit/a61196bfefeef48a3edd74c9fe2a9ce70149f9af 
Попробуйте переопределить его вручную, запустив в файлменеджере скрипт (текстовый файл названный change_refresh.sh и содержащий следующие строки): 

#!/bin/sh
echo -n 2 > /.eView/refresh_type

И посмотрите после этого в логе eView наличие строки "Reading refresh_type from /.eView/refresh_type (2)"

Прошу прощения за возможные неточности, пишу всё по памяти (сейчас книги под рукой нет).

Спасибо за отчёт об ошибке, надеюсь на дальнейшее сотрудничество в решении её.

**Comment by viteo** [comment]
Удалось изменить значение на (2), в логе отобразилось:
Reading refresh_type from /.eView/refresh_type (2)
Но экран все так же не обновляется.
Прошивка данная на базе Qt.

спасибо за помощь.

p.s. около года назад (уже не помню на какой из версий eview), на одной из предыдущих прошивок (тоже на базе Qt) был другой баг: экран обновлялся на каждое второе нажатие кнопки (будь то вверх-вниз, или кнопка меню, или любая другая). может эта информация может как-то помочь.

**Comment by S-trace** [comment]
Хорошо, я попробую через несколько дней собрать 064t2, выпилив автодетект 
обновления. Подождёте?

Отправлено из AquaMail для Андроида
http://www.aqua-mail.com

**Comment by viteo** [comment]
Да, конечно. Большое спасибо.

**Comment by S-trace** [comment]
Прошу прощения за долгое ожидание. 
Собрал версию, в которой выбор режима обновления (старый/новый) осуществляется по принципу GTK=старый, Qt=новый, как было когда-то. В остальном изменений относительно 064t2 нет. 
Взять можно тут: https://dl.dropboxusercontent.com/u/100376233/eView/eView064t2_legacy_refresh_detection.zip

**Comment by viteo** [comment]
Попробовал. Результат не изменился - экран черный.
eView_remover.sh использовал, заново переустановил, но экран по прежнему черный, обновление происходит при передергивании провода. когда провод вставляю и выхожу из программы, после ее закрытия висит предложение "Подсоединить книгу к компьютеру?". Т.е. это окошко, быть может, отрисовывается под окном программы, тем самым обновляя весь экран принудительно?
в логе Reading refresh_type from /.eView/refresh_type (1)

**Comment by S-trace** [comment]
Да, это окошко действительно рисуется снизу окна eView. 

Ладно, чтобы не гадать на кофейной гуще, когда же сломалось обновление экрана на вашей книге я собрал бинарники для каждого коммита в этом GIT (очень надеюсь, что сломалось оно не раньше, чем код был перенесён в этот репозиторий). 

https://dl.dropboxusercontent.com/u/100376233/eView/eView_builds.7z - вот архив со всеми билдами, проверьте пожалуйста бинарники (желательно чистить конфигурацию перед запуском каждый раз, для чистоты эксперимента) и определите, на каком из них обновление экрана ещё работало, и на каком уже перестало? Нужно выяснить хэш коммита, сломавшего обновление экрана.

В архиве директории имеют имена типа 000_2a01ac7e37c8b64c639f62fce472b9611acfc8a5 (по принципу "НомерКоммита_ХэшКоммита", где номера начинаются с самого старого pre-062 и заканчиваются новейшим 064t2).

Спасибо.

**Comment by viteo** [comment]
Путем бинарного поиска, я нашел его :)
Версия 107_e618a22cfbd902aa03946920e49fc44da622d0b2 запускается и экран корректно отображает информацию,в файл-менеджере вхожу в папки, открываю картинки. Единственное что: при включении меню или в опциях не видно, на что нажимаю. Т.е. выделение пункта исчезает, если я перемещаюсь вниз-вверх по меню. Если жму на аппаратную кнопку обновления экрана, он обновляется, и выделенный пункт меню становится опять виден.
А вот уже в 108_a61196bfefeef48a3edd74c9fe2a9ce70149f9af экран черный, как и в последних версиях. Помогает лишь передергивание шнура.

**Comment by viteo** [comment]
Добрый день, еще раз!
Читал и бед не знал на версии 107, но вот перешел на другой комикс, а там страницы побольше - и вертикально их читать неудобно. Поэтому включил в настройках "поворот станицы", картинка повернулась - видно отлично, полстраницы обозреваю - но вперед комикс не листается. Т.е. при нажатии кнопки листания обновляется экран, но он отображает все тот уже участок. Назад листает, показывает половину предыдущей страницы, но вперед - нет. Пробовал и умное листание, и читать как мангу - результат тот же. С помощью передергивания шнура проверил, что так же происходит и на последней версии (064t2), а вот на версии 062 листает правильно. Однако при запуске 062 файл-менеджер располагается горизонтально на экране, и открывает картинку в альбомной ориентации. А если включить опцию "поворот экрана", то комикс вовсе переворачивается вверх-ногами, относительно вертикального положения книги. Пропорции немного искажает, да и кнопки "усиление контраста" не хватает)

**Comment by S-trace** [comment]
Доброго времени суток. 

Прошу прощения, но сейчас у меня больше нет устройства, на котором я могу тестировать свои экспериментальные сборки (книга принесена в подарок). 

В планах есть приобретение совместимой книги с подсветкой и сенсорным экраном (дабы разрабатывать и тестировать в том числе и эти возможности), но пока я вряд ли смогу собрать что-то хорошее вслепую. 

Спасибо за интерес к проекту. Как только что-то изменится - я дам знать.

Пользователь Viktor notifications@github.com писал:

**Comment by S-trace** [comment]
Пользователь Viktor notifications@github.com писал:

**Comment by S-trace** [comment]
Приобрёл Gmini MagickBook T6LHD - что радует,  эта проблема присутствует. Будем исправлять.

**Comment by S-trace** [comment]
https://www.dropbox.com/s/jhxduhmf1jyfygs/eView064t3.zip?dl=1 - кажется, исправил.

**Comment by S-trace** [comment]
Перед тестированием желательно грохнуть старую конфигурацию скриптом eView_remover.

**Comment by viteo** [comment]
Подтверждаю) Работает! Черный экран сменяет сообщение "Пожалуйста подождите", а потом показывается ФМ.

К сожалению, пока что не могу проверить ошибку насчет листания повернутых картинок. За последние три месяца у меня вышли из стоя кнопки HOME, а за ней MENU. Если без первой можно жить и не замечать, то без второй уж практически никак.
После разборки книги стало ясно, что спроектирована она не самым удачным образом. Одна плата накатывается на другую и линии дорожек кнопок по бОльшей плате уходят под малую. Видимо, где-то там и потерялся контакт. Просто прогреть не получится из-за обвески малой платы. Пока единственным вариантом вижу переназначить кнопку MENU на кнопку обновления экрана, да все никак не выходит залезть в корень файловой системы книжки, чтобы хотя бы глянуть содержимое. Я больше по железу, чем по программированию) Да и скорее убунтовод я, чем линуксоид :)

Спасибо за возвращение в проект!

**Comment by viteo** [comment]
И выход из eView у меня теперь только через кнопку Reboot xD

**Comment by S-trace** [comment]
http://4pda.ru/forum/index.php?showtopic=550335&view=findpost&p=37564707 - здесь я выложил пакет запускающий adb на книге. Полагаю, он сработает и на Digma e605.

**Comment by S-trace** [comment]
А по поводу кнопок: платку видел, поразился полёту китайского инжиниринга. Как разведены левые и правые боковые кнопки, их дорожки запараллелены аппарато, или же всё в ядре сделано? Могу поиграться с раскладкой кнопок на своей книге, если интересно. Но, думаю, это уже следует обсуждать где-нибудь в другом месте (к примеру в ЛС на том же 4pda.ru)

**Comment by ReDetection** [comment]
@S-trace земляк, а не мог бы ты выложить adb тоже на дропбокс, ну или ещё куда-нибудь? на 4pda файл умер :( 
зы. за eView отдельный :+1:

**Comment by S-trace** [comment]
Он не умер, там просто надо зарегистрироваться на форуме чтобы что-то скачать. Иначе - ошибка 404 на любой файл.

**Comment by ReDetection** [comment]
@S-trace во как. ясно, спасибо!
